#!/bin/bash

homeDir=${HOME}
defaultBackupPath=${HOME}/homebridgeBackup

echo "Uninstalling Homebridge and every dependencies? (Y/N)"
read uninstall
if [ "$uninstall" == "Y" -o "$uninstall" == "y" ] 
then 
	echo "Stopping Homebridge Service"
	sudo systemctl stop homebridge
	echo "Uninstall Homebridge Plugins"
	sudo npm uninstall -g homebridge-*
	echo "Uninstall homebridge"
	sudo npm uninstall -g homebridge
	echo "Uninstall npm"
	sudo npm uninstall -g npm
	echo "Removing Service Files etc."
	sudo rm /etc/systemd/system/homebridge.service
	sudo rm /etc/default/homebridge
	echo "Do you want to save your current config.json as a Backup? (Y/N)"
	read backupConfig
	if [ "$backupConfig" == "Y" -o "$backupConfig" == "y" ]
	then 
		echo "This config.json will be backed up if you confirm"
		sudo jq '.' /var/homebridge/config.json
		read -p "Save this config.json? (Y/N)"		
		echo "Where do you want to store your backup? Please provide a absolute Path (/home/pi/Documents/backup e.g.)"
		echo "If you provide no Path the default path ($defaultBackupPath) will be used"
		read backupPath
		if [ "$backupPath" != "" ]
		then 
			echo "Copying your config.json to $backupPath"
			if [ -e $backupPath ];
			then
				sudo cp /var/homebridge/config.json $backupPath/$(date +%Y-%m-%d_%H-%M-%S)_config.json.bak
			else
				sudo mkdir -p $backupPath
				sudo chmod 0777 $backupPath
				sudo cp /var/homebridge/config.json $backupPath/$(date +%Y-%m-%d_%H-%M-%S)_config.json.bak
			fi
		else
			echo "Copying your config.json to $defaultBackupPath"
			if [ -e $defaultBackupPath ];
			then
				sudo cp /var/homebridge/config.json $defaultBackupPath/$(date +%Y-%m-%d_%H-%M-%S)_config.json.bak
			else 
				sudo mkdir -p $defaultBackupPath
				sudo chmod 0777 $defaultBackupPath
				sudo cp /var/homebridge/config.json $defaultBackupPath/$(date +%Y-%m-%d_%H-%M-%S)_config.json.bak
			fi
		fi
	fi
	sudo rm /var/homebridge -r
	echo "Deleting homebridge User"
	sudo rm /etc/sudoers.d/011_homebridge_nopasswd
	sudo deluser homebridge
	echo "Removing Service Shortcuts from Desktop"
	sudo rm $homeDir/Desktop/HomebridgeRestart
	sudo rm $homeDir/Desktop/HomebridgeStart
	sudo rm $homeDir/Desktop/HomebridgeStop
	sudo rm $homeDir/Desktop/HomebridgeLog
	echo "Uninstall libavahi libdnssd"
	sudo apt-get purge libavahi-compat-libdnssd-dev -y
	echo "Uninstall nodejs"
	sudo apt-get purge nodejs

	echo "Cleaning up old stuff"
	sudo apt-get autoremove -y
	sudo apt-get autoclean -y
	echo "Uninstall complete"
	echo "Do you want to reboot your Raspberry Pi? (Y/N)"
	read rebootNow
	if [ "$rebootNow" == "Y" -o "$rebootNow" == "y" ]
	then
		echo "Rebooting your Raspberry Pi in a few seconds..."
		sleep 10
		sudo reboot
	fi
else
	echo "No Uninstall selected"
fi
read -p "Press any Key to exit the script" exit